version: '3'

volumes:
  pg_data:

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: confy
      POSTGRES_PASSWORD: confy01