management:
    server:
        servlet:
            context-path: /management

spring:
    application:
        name: confy

    data:
        rest:
            basePath: /api

    jpa:
        hibernate:
            ddl-auto: none
    security:
        user:
            password: test1234

