version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "build.gradle" }}
      - run: ./gradlew assemble
      - save_cache:
          paths:
            - ~/.gradle
          key: circleci-demo-java-spring-{{ checksum "build.gradle" }}
      - run: ./gradlew build
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/libs/confy-*.jar
  integration-test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: .circleci/scripts/setup-integration-environment.sh
      - run: .circleci/scripts/teardown-integration-environment.sh

workflows:
  main:
    jobs:
      - build
      - integration-test
