version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - restore_cache:
          key: confy-{{ checksum "build.gradle" }}
      - run: ./gradlew assemble      
      - save_cache:
          paths:
            - ~/.gradle
          key: confy-spring-{{ checksum "build.gradle" }}      
      - run: ./gradlew build      
      - store_test_results:
          path: build/test-results/test      
      - store_artifacts:
          path: build/libs/confy-*.jar          
      - run: bash <(curl -s https://codecov.io/bash)