version: 2
executorType: machine
jobs:
  build:

    steps:
      - checkout

      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "build.gradle" }}
      
      - run: ./gradlew assemble
      
      - save_cache:
          paths:
            - ~/.gradle
          key: circleci-demo-java-spring-{{ checksum "build.gradle" }}

      - run: ./gradlew build
      
      - store_test_results:
          path: build/test-results/test
      
      - store_artifacts:
          path: build/libs/confy-*.jar
