name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build

      - name: Submit code coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./build/reports/jacoco/test/*.xml
          name: codecov
