name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: 8.0.282+8 
      - name: Build with Gradle
        run: ./gradlew build

      - name: Submit code coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./build/reports/jacoco/test/*.xml
          name: codecov
